spring.application.name=gateway
spring.cloud.consul.discovery.register=true
spring.cloud.consul.host=consul
spring.cloud.consul.discovery.prefer-ip-address=true
spring.cloud.consul.discovery.instance-id=${spring.application.name}:${spring.cloud.client.hostname}:${random.int[1,999999]}
spring.cloud.consul.discovery.enabled=false
spring.config.import=optional:consul:consul
server.port=${SERVER_PORT:8000}
spring.cloud.consul.config.format=yaml



jwt.token.validity=18000
jwt.signing.key=wELa5KTuEKoo-md8qyeYiWxeM8emOTzlB8fJH2EF4Bu8
jwt.authorities.key=roles
jwt.token.prefix=Bearer
jwt.header.string=Authorization
key.public:secret-key=
